on: [pull_request]

name: Test ChatGPT

permissions:
  pull-requests: write
  contents: write
  issues: write

jobs:
  codeguard:
    runs-on: ubuntu-latest
    name: ChatGPT review PR
    steps:
      - name: ChatGPT review PR
        uses: jacopocarlini/codeguard-gpt-action@HEAD
        with:
          number: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CODEGUARD_COMMENT_BY_LINE: true
